import type { Card } from '../types.ts';

/**
 * Challenge cards. Everything here is doable sitting around a table, indoors,
 * with no equipment and no risk of anybody getting hurt.
 */
export const challengeCards: readonly Card[] = [
  {
    id: 'cha-01',
    category: 'challenges',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, speak only in questions until your next turn.',
    alcoholFree: true,
  },
  {
    id: 'cha-02',
    category: 'challenges',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, sell the nearest object to the group as if it were a luxury item.',
    duration: 30,
    alcoholFree: true,
  },
  {
    id: 'cha-03',
    category: 'challenges',
    intensity: 'relaxed',
    audience: 'pair',
    text: '{player} and {otherPlayer}, hold eye contact until one of you laughs.',
    alcoholFree: true,
  },
  {
    id: 'cha-04',
    category: 'challenges',
    intensity: 'relaxed',
    audience: 'group',
    text: 'Everyone names a city in turn without repeating. The first person to stall starts the next card.',
    alcoholFree: true,
  },
  {
    id: 'cha-05',
    category: 'challenges',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, hum a song. The first person in {playerList} to name it chooses the next drink refill.',
    alcoholFree: true,
  },
  {
    id: 'cha-06',
    category: 'challenges',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, give a weather forecast for this room in the style of a sports commentator.',
    duration: 20,
    alcoholFree: true,
  },
  {
    id: 'cha-07',
    category: 'challenges',
    intensity: 'relaxed',
    audience: 'pair',
    text: '{player} and {otherPlayer}, swap one item of clothing or accessory, if you both agree.',
    alcoholFree: true,
  },
  {
    id: 'cha-08',
    category: 'challenges',
    intensity: 'relaxed',
    audience: 'group',
    text: 'Everyone strikes a pose for a group photo. Nobody has to be in it.',
    alcoholFree: true,
  },
  {
    id: 'cha-09',
    category: 'challenges',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, describe your job or your studies badly enough that nobody can guess it.',
    alcoholFree: true,
  },
  {
    id: 'cha-10',
    category: 'challenges',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, compliment everyone in {playerList} in one single breath.',
    alcoholFree: true,
  },
  {
    id: 'cha-11',
    category: 'challenges',
    intensity: 'relaxed',
    audience: 'group',
    text: 'Everyone must answer the next card in an accent of their choosing.',
    alcoholFree: true,
  },
  {
    id: 'cha-12',
    category: 'challenges',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, invent a cocktail or mocktail name based on how tonight is going.',
    alcoholFree: true,
  },
  {
    id: 'cha-13',
    category: 'challenges',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, do your best catwalk to the nearest wall and back.',
    alcoholFree: true,
  },
  {
    id: 'cha-14',
    category: 'challenges',
    intensity: 'standard',
    audience: 'pair',
    text: '{player} and {otherPlayer}, have a conversation in complete gibberish. The group narrates what you are saying.',
    duration: 30,
    alcoholFree: true,
  },
  {
    id: 'cha-15',
    category: 'challenges',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, recreate a famous film scene using only the objects on the table.',
    duration: 45,
    alcoholFree: true,
  },
  {
    id: 'cha-16',
    category: 'challenges',
    intensity: 'standard',
    audience: 'group',
    text: 'Everyone in {playerList} does an impression of the person to their left, one after another.',
    alcoholFree: true,
  },
  {
    id: 'cha-17',
    category: 'challenges',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, sing the chorus of the last song you had stuck in your head. Anyone who joins in may take a sip.',
    alcoholFree: false,
    alcoholFreeText:
      '{player}, sing the chorus of the last song you had stuck in your head. Anyone who joins in earns a round of applause.',
  },
  {
    id: 'cha-18',
    category: 'challenges',
    intensity: 'standard',
    audience: 'pair',
    text: '{player} and {otherPlayer}, mirror each other’s movements. The group decides who broke first.',
    duration: 30,
    alcoholFree: true,
  },
  {
    id: 'cha-19',
    category: 'challenges',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, deliver a motivational speech to your own drink.',
    duration: 20,
    alcoholFree: true,
  },
  {
    id: 'cha-20',
    category: 'challenges',
    intensity: 'standard',
    audience: 'group',
    text: 'Group challenge: build the tallest tower you can from things within arm’s reach.',
    duration: 60,
    alcoholFree: true,
  },
  {
    id: 'cha-21',
    category: 'challenges',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, text someone outside this room a sincere compliment. Read it out first, and only send it if you want to.',
    alcoholFree: true,
  },
  {
    id: 'cha-22',
    category: 'challenges',
    intensity: 'standard',
    audience: 'pair',
    text: '{player} interviews {otherPlayer} as a talk show host for thirty seconds. Applause is mandatory.',
    duration: 30,
    alcoholFree: true,
  },
  {
    id: 'cha-23',
    category: 'challenges',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, describe the plot of your favourite film so badly that it sounds terrible.',
    alcoholFree: true,
  },
  {
    id: 'cha-24',
    category: 'challenges',
    intensity: 'standard',
    audience: 'group',
    text: 'Everyone votes with a thumb up or down on whether {player} could win a dance-off. {player} dances either way.',
    alcoholFree: true,
  },
  {
    id: 'cha-25',
    category: 'challenges',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, let the person on your right choose a new voice for you to use until your next turn.',
    alcoholFree: true,
  },
  {
    id: 'cha-26',
    category: 'challenges',
    intensity: 'chaotic',
    audience: 'pair',
    text: '{player} and {otherPlayer}, perform a dramatic break-up scene about a missing snack.',
    duration: 45,
    alcoholFree: true,
  },
  {
    id: 'cha-27',
    category: 'challenges',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, do an interpretive dance of your morning routine. No explanation allowed.',
    duration: 30,
    alcoholFree: true,
  },
  {
    id: 'cha-28',
    category: 'challenges',
    intensity: 'chaotic',
    audience: 'group',
    text: 'Everyone in {playerList} makes their most convincing animal noise at once. Loudest gets to pick the next rule.',
    alcoholFree: true,
  },
  {
    id: 'cha-29',
    category: 'challenges',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, roast yourself for twenty seconds. The group is not allowed to join in.',
    duration: 20,
    alcoholFree: true,
  },
  {
    id: 'cha-30',
    category: 'challenges',
    intensity: 'chaotic',
    audience: 'pair',
    text: '{player} and {otherPlayer}, invent a chant for this group and teach it to everyone.',
    duration: 45,
    alcoholFree: true,
  },
  {
    id: 'cha-31',
    category: 'challenges',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, act out the most recent emoji you sent until someone guesses it.',
    alcoholFree: true,
  },
  {
    id: 'cha-32',
    category: 'challenges',
    intensity: 'chaotic',
    audience: 'group',
    text: 'Everyone swaps seats one place to the left. Anyone who ends up somewhere better may take a sip.',
    alcoholFree: false,
    alcoholFreeText:
      'Everyone swaps seats one place to the left. Anyone who ends up somewhere better announces it smugly.',
  },
  {
    id: 'cha-33',
    category: 'challenges',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, narrate what everyone in the room is doing as if it were a wildlife documentary.',
    duration: 30,
    alcoholFree: true,
  },
  {
    id: 'cha-34',
    category: 'challenges',
    intensity: 'chaotic',
    audience: 'pair',
    text: '{player} and {otherPlayer}, arm wrestle with your non-dominant hands, gently. A draw is a perfectly good outcome.',
    alcoholFree: true,
  },
  {
    id: 'cha-35',
    category: 'challenges',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, give the group a tour of this room as an unusually enthusiastic estate agent.',
    duration: 45,
    alcoholFree: true,
  },
  {
    id: 'cha-36',
    category: 'challenges',
    intensity: 'chaotic',
    audience: 'group',
    text: 'The whole group invents a slow-motion action scene together. Someone should film it.',
    duration: 60,
    alcoholFree: true,
  },
];
