import type { Card } from '../types.ts';

/** Warm-up cards: low stakes, aimed at groups that have just sat down. */
export const icebreakerCards: readonly Card[] = [
  {
    id: 'ice-01',
    category: 'icebreakers',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, introduce yourself the way a film villain would. Everyone else guesses the film.',
    alcoholFree: true,
  },
  {
    id: 'ice-02',
    category: 'icebreakers',
    intensity: 'relaxed',
    audience: 'group',
    text: 'Everyone say their own name in the silliest voice they can manage. Nobody wins anything.',
    alcoholFree: true,
  },
  {
    id: 'ice-03',
    category: 'icebreakers',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, tell the group one true thing and one invented thing about yourself. The group guesses which is which.',
    alcoholFree: true,
  },
  {
    id: 'ice-04',
    category: 'icebreakers',
    intensity: 'relaxed',
    audience: 'pair',
    text: '{player} and {otherPlayer}, find something you both did this week that nobody else here did.',
    alcoholFree: true,
  },
  {
    id: 'ice-05',
    category: 'icebreakers',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, describe your entire day using exactly three words.',
    alcoholFree: true,
  },
  {
    id: 'ice-06',
    category: 'icebreakers',
    intensity: 'relaxed',
    audience: 'group',
    text: 'Anyone who feels like it shows the last photo they took. Passing is completely fine.',
    alcoholFree: true,
  },
  {
    id: 'ice-07',
    category: 'icebreakers',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, what is the most useless talent you have? Demonstrate it if you can.',
    alcoholFree: true,
  },
  {
    id: 'ice-08',
    category: 'icebreakers',
    intensity: 'relaxed',
    audience: 'pair',
    text: "{player}, guess {otherPlayer}'s go-to karaoke song. {otherPlayer} says how close you got.",
    alcoholFree: true,
  },
  {
    id: 'ice-09',
    category: 'icebreakers',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, name everyone here in the order you met them. {playerList} will correct you.',
    alcoholFree: true,
  },
  {
    id: 'ice-10',
    category: 'icebreakers',
    intensity: 'relaxed',
    audience: 'group',
    text: 'Everyone swap places with someone they have not properly talked to yet.',
    alcoholFree: true,
  },
  {
    id: 'ice-11',
    category: 'icebreakers',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, do a friendly impression of someone in this room. No names — the group guesses.',
    alcoholFree: true,
  },
  {
    id: 'ice-12',
    category: 'icebreakers',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, tell the story of the worst haircut you have ever had. Photographic evidence earns respect.',
    alcoholFree: true,
  },
  {
    id: 'ice-13',
    category: 'icebreakers',
    intensity: 'standard',
    audience: 'pair',
    text: '{player} and {otherPlayer}, invent a secret handshake before the timer runs out.',
    duration: 20,
    alcoholFree: true,
  },
  {
    id: 'ice-14',
    category: 'icebreakers',
    intensity: 'standard',
    audience: 'group',
    text: 'Everyone in {playerList} shares the last thing they searched for. Skip it if it is dull — or too revealing.',
    alcoholFree: true,
  },
  {
    id: 'ice-15',
    category: 'icebreakers',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, what nickname would you give yourself if you could start again tomorrow?',
    alcoholFree: true,
  },
  {
    id: 'ice-16',
    category: 'icebreakers',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, tell us something you were oddly proud of this week. Anyone with a similar story can take a sip if they want.',
    alcoholFree: false,
    alcoholFreeText:
      '{player}, tell us something you were oddly proud of this week. Anyone with a similar story gets one imaginary point.',
  },
  {
    id: 'ice-17',
    category: 'icebreakers',
    intensity: 'standard',
    audience: 'pair',
    text: '{player}, describe {otherPlayer} to a stranger in one kind sentence.',
    alcoholFree: true,
  },
  {
    id: 'ice-18',
    category: 'icebreakers',
    intensity: 'standard',
    audience: 'group',
    text: 'Everybody freeze in the pose that best describes their current mood and hold it.',
    duration: 5,
    alcoholFree: true,
  },
  {
    id: 'ice-19',
    category: 'icebreakers',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, what is one thing you believed for embarrassingly long?',
    alcoholFree: true,
  },
  {
    id: 'ice-20',
    category: 'icebreakers',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, give an acceptance speech for an award you have definitely not won.',
    duration: 30,
    alcoholFree: true,
  },
  {
    id: 'ice-21',
    category: 'icebreakers',
    intensity: 'chaotic',
    audience: 'group',
    text: 'Everyone change one thing about how they are sitting. The last person to move reveals a hidden talent.',
    alcoholFree: true,
  },
  {
    id: 'ice-22',
    category: 'icebreakers',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, read out the last message you sent in the voice of a news reader. Skip freely if it is private.',
    alcoholFree: true,
  },
  {
    id: 'ice-23',
    category: 'icebreakers',
    intensity: 'chaotic',
    audience: 'pair',
    text: '{player} and {otherPlayer}, argue about whether cereal counts as soup. The rest of {playerList} judges.',
    duration: 30,
    alcoholFree: true,
  },
  {
    id: 'ice-24',
    category: 'icebreakers',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, announce a fake news headline about tonight. If the group laughs, everyone may take a sip.',
    alcoholFree: false,
    alcoholFreeText:
      '{player}, announce a fake news headline about tonight. If the group laughs, everyone does a small victory pose.',
  },
];
