import type { Card } from '../types.ts';

/** Question cards: cheeky but never invasive, and always skippable. */
export const questionCards: readonly Card[] = [
  {
    id: 'que-01',
    category: 'questions',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, what is the pettiest reason you have stopped following someone online?',
    alcoholFree: true,
  },
  {
    id: 'que-02',
    category: 'questions',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, which fictional character would you happily share a flat with, and which one absolutely not?',
    alcoholFree: true,
  },
  {
    id: 'que-03',
    category: 'questions',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, what is the most unreasonable thing that has ever made you cry?',
    alcoholFree: true,
  },
  {
    id: 'que-04',
    category: 'questions',
    intensity: 'relaxed',
    audience: 'pair',
    text: '{otherPlayer} asks {player} any question they like. {player} may answer or pass.',
    alcoholFree: true,
  },
  {
    id: 'que-05',
    category: 'questions',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, what is a compliment you received that you still think about?',
    alcoholFree: true,
  },
  {
    id: 'que-06',
    category: 'questions',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, what is your most controversial food opinion? Defend it.',
    alcoholFree: true,
  },
  {
    id: 'que-07',
    category: 'questions',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, which app would you delete forever if it cost you nothing?',
    alcoholFree: true,
  },
  {
    id: 'que-08',
    category: 'questions',
    intensity: 'relaxed',
    audience: 'pair',
    text: '{player}, tell {otherPlayer} the first thing you remember thinking about them.',
    alcoholFree: true,
  },
  {
    id: 'que-09',
    category: 'questions',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, what is the smallest thing that ruins your entire morning?',
    alcoholFree: true,
  },
  {
    id: 'que-10',
    category: 'questions',
    intensity: 'relaxed',
    audience: 'individual',
    text: '{player}, what hobby have you pretended to be into just to fit in?',
    alcoholFree: true,
  },
  {
    id: 'que-11',
    category: 'questions',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, what is the worst piece of advice you have ever confidently given?',
    alcoholFree: true,
  },
  {
    id: 'que-12',
    category: 'questions',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, describe your worst first date in under thirty seconds.',
    duration: 30,
    alcoholFree: true,
  },
  {
    id: 'que-13',
    category: 'questions',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, what is something you pretend to understand every time it comes up?',
    alcoholFree: true,
  },
  {
    id: 'que-14',
    category: 'questions',
    intensity: 'standard',
    audience: 'pair',
    text: '{player} and {otherPlayer}, each name one thing you would swap about your lives. Anyone who agrees may take a sip.',
    alcoholFree: false,
    alcoholFreeText:
      '{player} and {otherPlayer}, each name one thing you would swap about your lives. Anyone who agrees raises a hand.',
  },
  {
    id: 'que-15',
    category: 'questions',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, what is the most money you have wasted on something you used once?',
    alcoholFree: true,
  },
  {
    id: 'que-16',
    category: 'questions',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, what rumour about you turned out to be weirdly flattering?',
    alcoholFree: true,
  },
  {
    id: 'que-17',
    category: 'questions',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, what is the pettiest argument you have ever won?',
    alcoholFree: true,
  },
  {
    id: 'que-18',
    category: 'questions',
    intensity: 'standard',
    audience: 'pair',
    text: '{player}, guess the most embarrassing song in {otherPlayer}’s recent listening. {otherPlayer} confirms or denies.',
    alcoholFree: true,
  },
  {
    id: 'que-19',
    category: 'questions',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, what is a small lie you tell almost every week?',
    alcoholFree: true,
  },
  {
    id: 'que-20',
    category: 'questions',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, which of your habits would drive a flatmate up the wall? {playerList} may agree loudly.',
    alcoholFree: true,
  },
  {
    id: 'que-21',
    category: 'questions',
    intensity: 'standard',
    audience: 'individual',
    text: '{player}, what is the most dramatic thing you have done to avoid a phone call?',
    alcoholFree: true,
  },
  {
    id: 'que-22',
    category: 'questions',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, what is the worst thing you have ever said out loud by accident?',
    alcoholFree: true,
  },
  {
    id: 'que-23',
    category: 'questions',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, describe the most chaotic night out you are willing to talk about. Details optional.',
    alcoholFree: true,
  },
  {
    id: 'que-24',
    category: 'questions',
    intensity: 'chaotic',
    audience: 'pair',
    text: '{player}, tell {otherPlayer} one thing you genuinely admire about them and one thing you would never copy.',
    alcoholFree: true,
  },
  {
    id: 'que-25',
    category: 'questions',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, what is the story behind your least favourite photo of yourself?',
    alcoholFree: true,
  },
  {
    id: 'que-26',
    category: 'questions',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, what is the boldest thing you have ever texted and immediately regretted?',
    alcoholFree: true,
  },
  {
    id: 'que-27',
    category: 'questions',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, confess a strong opinion you hold about someone in {playerList}. Keep it kind.',
    alcoholFree: true,
  },
  {
    id: 'que-28',
    category: 'questions',
    intensity: 'chaotic',
    audience: 'pair',
    text: '{player} and {otherPlayer}, each admit one thing you have borrowed and never returned. Anyone still waiting may take a sip.',
    alcoholFree: false,
    alcoholFreeText:
      '{player} and {otherPlayer}, each admit one thing you have borrowed and never returned. Anyone still waiting gets an apology.',
  },
  {
    id: 'que-29',
    category: 'questions',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, what is the most elaborate excuse you have ever invented to leave early?',
    alcoholFree: true,
  },
  {
    id: 'que-30',
    category: 'questions',
    intensity: 'chaotic',
    audience: 'individual',
    text: '{player}, which unpopular thing do you secretly enjoy and refuse to apologise for?',
    alcoholFree: true,
  },
];
