import type { Card } from '../types.ts';

/**
 * Rule cards create a temporary rule that stays pinned on screen until someone
 * removes it. Keep rules short: they have to be readable at a glance.
 */
export const ruleCards: readonly Card[] = [
  {
    id: 'rul-01',
    category: 'rules',
    intensity: 'relaxed',
    audience: 'rule',
    text: 'New rule: nobody may use first names. Everyone is "friend" until this rule is removed.',
    rule: 'No first names — everyone is "friend".',
    alcoholFree: true,
  },
  {
    id: 'rul-02',
    category: 'rules',
    intensity: 'relaxed',
    audience: 'rule',
    text: 'New rule: {player} is the official timekeeper and announces how long each card takes.',
    rule: '{player} is the timekeeper.',
    alcoholFree: true,
  },
  {
    id: 'rul-03',
    category: 'rules',
    intensity: 'relaxed',
    audience: 'rule',
    text: 'New rule: every answer must end with "allegedly".',
    rule: 'Every answer ends with "allegedly".',
    alcoholFree: true,
  },
  {
    id: 'rul-04',
    category: 'rules',
    intensity: 'relaxed',
    audience: 'rule',
    text: 'New rule: {player} chooses a word that nobody is allowed to say.',
    rule: '{player} banned a word. Do not say it.',
    alcoholFree: true,
  },
  {
    id: 'rul-05',
    category: 'rules',
    intensity: 'relaxed',
    audience: 'rule',
    text: 'New rule: anyone who checks their phone owes the group one fun fact.',
    rule: 'Phone check = one fun fact.',
    alcoholFree: true,
  },
  {
    id: 'rul-06',
    category: 'rules',
    intensity: 'relaxed',
    audience: 'rule',
    text: 'New rule: applause is mandatory after every card. {playerList} sets the standard.',
    rule: 'Applause after every card.',
    alcoholFree: true,
  },
  {
    id: 'rul-07',
    category: 'rules',
    intensity: 'standard',
    audience: 'rule',
    text: 'New rule: {player} may hand out one compliment per card, and must never repeat one.',
    rule: '{player} gives one new compliment per card.',
    alcoholFree: true,
  },
  {
    id: 'rul-08',
    category: 'rules',
    intensity: 'standard',
    audience: 'rule',
    text: 'New rule: no pointing. Describe people instead.',
    rule: 'No pointing — describe people instead.',
    alcoholFree: true,
  },
  {
    id: 'rul-09',
    category: 'rules',
    intensity: 'standard',
    audience: 'rule',
    text: 'New rule: everyone must raise a glass before answering. Anyone who forgets may take a sip, or simply say "cheers".',
    rule: 'Raise a glass before answering.',
    alcoholFree: false,
    alcoholFreeText:
      'New rule: everyone must raise a glass and say "cheers" before answering. Anyone who forgets starts again.',
    alcoholFreeRule: 'Say "cheers" before answering.',
  },
  {
    id: 'rul-10',
    category: 'rules',
    intensity: 'standard',
    audience: 'rule',
    text: 'New rule: {player} is now the narrator and must announce every card out loud in a dramatic voice.',
    rule: '{player} narrates every card dramatically.',
    alcoholFree: true,
  },
  {
    id: 'rul-11',
    category: 'rules',
    intensity: 'standard',
    audience: 'rule',
    text: 'New rule: questions may only be answered with a full sentence. One-word answers are forbidden.',
    rule: 'Full sentences only.',
    alcoholFree: true,
  },
  {
    id: 'rul-12',
    category: 'rules',
    intensity: 'standard',
    audience: 'rule',
    text: 'New rule: {player} picks a gesture. Everyone must copy it whenever a new card appears.',
    rule: 'Copy {player}’s gesture on every new card.',
    alcoholFree: true,
  },
  {
    id: 'rul-13',
    category: 'rules',
    intensity: 'chaotic',
    audience: 'rule',
    text: 'New rule: nobody may say "yes" or "no". Find another way.',
    rule: 'No "yes" and no "no".',
    alcoholFree: true,
  },
  {
    id: 'rul-14',
    category: 'rules',
    intensity: 'chaotic',
    audience: 'rule',
    text: 'New rule: every story must be told standing up.',
    rule: 'Stories are told standing up.',
    alcoholFree: true,
  },
  {
    id: 'rul-15',
    category: 'rules',
    intensity: 'chaotic',
    audience: 'rule',
    text: 'New rule: {player} invents a group catchphrase. Everyone must use it at least once per round.',
    rule: 'Use {player}’s catchphrase every round.',
    alcoholFree: true,
  },
  {
    id: 'rul-16',
    category: 'rules',
    intensity: 'chaotic',
    audience: 'rule',
    text: 'New rule: all laughter must be theatrical and far too loud.',
    rule: 'Laughter must be theatrical.',
    alcoholFree: true,
  },
  {
    id: 'rul-17',
    category: 'rules',
    intensity: 'chaotic',
    audience: 'rule',
    text: 'New rule: anyone who swears must immediately pay a compliment to the person on their left.',
    rule: 'Swearing costs one compliment.',
    alcoholFree: true,
  },
  {
    id: 'rul-18',
    category: 'rules',
    intensity: 'chaotic',
    audience: 'rule',
    text: 'New rule: whenever someone mentions this game by name, everyone may take a sip. Water counts.',
    rule: 'Game named = everyone may sip.',
    alcoholFree: false,
    alcoholFreeText:
      'New rule: whenever someone mentions this game by name, everyone must strike a pose and hold it for three seconds.',
    alcoholFreeRule: 'Game named = everyone poses.',
  },
];
