import type { Card } from '../types.ts';

/**
 * Vote cards. The group points on the count of three. Wording stays on the
 * playful side of teasing — never on the side of ganging up on someone.
 */
export const voteCards: readonly Card[] = [
  {
    id: 'vot-01',
    category: 'votes',
    intensity: 'relaxed',
    audience: 'vote',
    text: 'Vote: who in {playerList} would survive longest without their phone? Point on three.',
    alcoholFree: true,
  },
  {
    id: 'vot-02',
    category: 'votes',
    intensity: 'relaxed',
    audience: 'vote',
    text: 'Vote: who in {playerList} gives the best advice? Point on three, then let them give some.',
    alcoholFree: true,
  },
  {
    id: 'vot-03',
    category: 'votes',
    intensity: 'relaxed',
    audience: 'vote',
    text: 'Vote: who in {playerList} would be the best person to get lost in a new city with?',
    alcoholFree: true,
  },
  {
    id: 'vot-04',
    category: 'votes',
    intensity: 'relaxed',
    audience: 'vote',
    text: 'Vote: who in {playerList} has the most chaotic camera roll? They may show one photo of their choosing.',
    alcoholFree: true,
  },
  {
    id: 'vot-05',
    category: 'votes',
    intensity: 'relaxed',
    audience: 'vote',
    text: 'Vote: who in {playerList} would win a staring contest against a cat?',
    alcoholFree: true,
  },
  {
    id: 'vot-06',
    category: 'votes',
    intensity: 'relaxed',
    audience: 'vote',
    text: 'Vote: who in {playerList} is most likely to reply to a message three weeks later?',
    alcoholFree: true,
  },
  {
    id: 'vot-07',
    category: 'votes',
    intensity: 'relaxed',
    audience: 'vote',
    text: 'Vote: who in {playerList} has the most underrated laugh? Everyone demonstrates theirs first.',
    alcoholFree: true,
  },
  {
    id: 'vot-08',
    category: 'votes',
    intensity: 'relaxed',
    audience: 'vote',
    text: 'Vote: who in {playerList} would be first to adopt a completely unnecessary pet?',
    alcoholFree: true,
  },
  {
    id: 'vot-09',
    category: 'votes',
    intensity: 'standard',
    audience: 'vote',
    text: 'Vote: who in {playerList} tells the longest stories? The winner has thirty seconds to prove the group wrong.',
    duration: 30,
    alcoholFree: true,
  },
  {
    id: 'vot-10',
    category: 'votes',
    intensity: 'standard',
    audience: 'vote',
    text: 'Vote: who in {playerList} is most likely to start a business that nobody asked for? They pitch it now.',
    alcoholFree: true,
  },
  {
    id: 'vot-11',
    category: 'votes',
    intensity: 'standard',
    audience: 'vote',
    text: 'Vote: who in {playerList} would break first in a silence contest? The winner may take a sip if they want.',
    alcoholFree: false,
    alcoholFreeText:
      'Vote: who in {playerList} would break first in a silence contest? The winner must stay quiet for one whole card.',
  },
  {
    id: 'vot-12',
    category: 'votes',
    intensity: 'standard',
    audience: 'vote',
    text: 'Vote: who in {playerList} has the most unhinged shopping habits? They defend one recent purchase.',
    alcoholFree: true,
  },
  {
    id: 'vot-13',
    category: 'votes',
    intensity: 'standard',
    audience: 'vote',
    text: 'Vote: who in {playerList} would be the worst person to share a hotel room with, and who would be the best?',
    alcoholFree: true,
  },
  {
    id: 'vot-14',
    category: 'votes',
    intensity: 'standard',
    audience: 'vote',
    text: 'Vote: who in {playerList} is the most competitive? Whoever wins the vote has clearly proven the point.',
    alcoholFree: true,
  },
  {
    id: 'vot-15',
    category: 'votes',
    intensity: 'standard',
    audience: 'vote',
    text: 'Vote: who in {playerList} would make the best film character? The group names the genre.',
    alcoholFree: true,
  },
  {
    id: 'vot-16',
    category: 'votes',
    intensity: 'standard',
    audience: 'vote',
    text: 'Vote: who in {playerList} gives the most confident wrong answers?',
    alcoholFree: true,
  },
  {
    id: 'vot-17',
    category: 'votes',
    intensity: 'standard',
    audience: 'vote',
    text: 'Vote: who in {playerList} would you trust with the aux cable for an entire road trip?',
    alcoholFree: true,
  },
  {
    id: 'vot-18',
    category: 'votes',
    intensity: 'chaotic',
    audience: 'vote',
    text: 'Vote: who in {playerList} has the best worst dance move? Everyone who voted for them must copy it.',
    alcoholFree: true,
  },
  {
    id: 'vot-19',
    category: 'votes',
    intensity: 'chaotic',
    audience: 'vote',
    text: 'Vote: who in {playerList} is most likely to have a secret second life? They invent it on the spot.',
    alcoholFree: true,
  },
  {
    id: 'vot-20',
    category: 'votes',
    intensity: 'chaotic',
    audience: 'vote',
    text: 'Vote: who in {playerList} would cause the most drama in a group holiday chat? Anyone in the minority may take a sip.',
    alcoholFree: false,
    alcoholFreeText:
      'Vote: who in {playerList} would cause the most drama in a group holiday chat? Anyone in the minority explains their vote.',
  },
  {
    id: 'vot-21',
    category: 'votes',
    intensity: 'chaotic',
    audience: 'vote',
    text: 'Vote: who in {playerList} tells the boldest stories? The runner-up gets to tell one now.',
    alcoholFree: true,
  },
  {
    id: 'vot-22',
    category: 'votes',
    intensity: 'chaotic',
    audience: 'vote',
    text: 'Vote: who in {playerList} would win a debate on absolutely no preparation? Give them a topic.',
    alcoholFree: true,
  },
  {
    id: 'vot-23',
    category: 'votes',
    intensity: 'chaotic',
    audience: 'vote',
    text: 'Vote: who in {playerList} is most likely to reinvent themselves entirely next year? They describe the new version.',
    alcoholFree: true,
  },
  {
    id: 'vot-24',
    category: 'votes',
    intensity: 'chaotic',
    audience: 'vote',
    text: 'Vote: who in {playerList} would be the ringleader if this group committed to something spectacularly silly?',
    alcoholFree: true,
  },
];
